### ISSUE TITLE
[Crash] Condition Zero Deleted Scenes 

### ISSUE THREAD

**Issue by lespaul64** [LAGonauta/MetaAudio#23]
The game crash on 1st cut scene audio been played.

Details:
] version
Protocol version 48
Exe version 1.0.0.0 (czerorr)
Exe build: 15:17:55 Jul 24 2019 (8308)

] al_version 
Meta Audio Version: 92b7efb1ffebb94e3d20ed89f6dd72b50264b16f
 OpenAL Device: OpenAL Soft on Output BlasterX G1 (Sound BlasterX G1)
 OpenAL Version: 1.1

That's all, thank you.

**Comment by LAGonauta** [comment]
Yeah, that is a known bug since engine 8279. I won't be able to fix it as I would need to go deep into CS: CZ Delete Scenes compiled code, however I am not able to do that.

Anyone else is welcome to try :)

**Comment by hzqst** [comment]
## Cause

This is because the two signatures :

 `#define SEQUENCE_GETSENTENCEBYINDEX_SIG "\x56\x8B\x35\x2A\x2A\x2A\x2A\x85\xF6\x57\x74\x2A\x8B\x7C\x24\x0C\x8B\x06\x57\x50\xE8"`

 and 

`#define SEQUENCE_GETSENTENCEBYINDEX_SIG_NEW "\x55\x8B\xEC\x56\x8B\x35\x2A\x2A\x2A\x2A\x85\xF6\x57\x74\x2A\x8B\x7D\x08\x8B\x06\x57\x50\xE8"`

was pointing to

`sentenceGroupEntry_s *__cdecl Sequence_FindSentenceGroup(const char *Str2)` who takes string as first argument

![image](https://user-images.githubusercontent.com/12287588/126753967-7dbc1ea2-8082-4876-be71-1ed787533559.png)

instead of 

`sentenceEntry_s *__cdecl SequenceGetSentenceByIndex(unsigned int a1)` who takes integer as first argument

![image](https://user-images.githubusercontent.com/12287588/126753987-2ee5dc77-d4fa-4b24-ba72-43c9568d5e50.png)

which would finally crash game at

https://github.com/LAGonauta/MetaAudio/blob/6b85d170aa45814ad15f82aaeecdc77ffe163ac6/src/Vox/VoxManager.cpp#L238

## Fix

Using correct sigs should solve the crash.

`#define SEQUENCE_GETSENTENCEBYINDEX_SIG_NEW "\x55\x8B\xEC\xA1\x2A\x2A\x2A\x2A\x33\xC9\x85\xC0\x2A\x2A\x2A\x8B\x75\x08\x8B\x50\x04"`

`#define SEQUENCE_GETSENTENCEBYINDEX_SIG "\xA1\x2A\x2A\x2A\x2A\x33\xC9\x85\xC0\x2A\x2A\x2A\x2A\x2A\x24\x08\x8B\x50\x04"`

It found the correct sentense entry and no crash happened after changing to correct signatures.

![image](https://user-images.githubusercontent.com/12287588/126753606-a9772a79-a506-40e3-aa68-6b631c15e749.png)

Tested in 8684 and works fine with CZ:DS

![54444](https://user-images.githubusercontent.com/12287588/126754670-107fedf3-4796-4284-ba86-1d8b5619a89b.png)

**Comment by LAGonauta** [comment]
Should be fixed with https://github.com/LAGonauta/MetaAudio/pull/36
